apiVersion: v1
kind: Pod
metadata:
  name: my-nginx-pod
  labels:
    app: nginx
spec:
  containers:
  - image: nginx:1.18
    name: my-nginx-container
    ports:
    - containerPort: 80
    env:
      name: FIRST_ENV_VAR
      value: "First environment variable"
      name: SECOND_ENV_VAR
      value: "Second environment variable"
    # the "command" below overides the ENTRYPOINT instruction in the Docker image
    # and the "args" overides the CMD instruction in the Docker image
    # command:
    #   - sleep
    #   - "300"
    # or 
    # command: ["printenv"] or 
    # command:
    # - printenv
    # args: ["HOSTNAME", "KUBERNETES_PORT"] or
    # args:
    # - HOSTNAME
    # - KUBERNETES_PORT
  restartPolicy: Always